[2024-10-19T21:19:58.024+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_linkedin_pipeline.s3_upload_linkedin manual__2024-10-19T21:19:45.171984+00:00 [queued]>
[2024-10-19T21:19:58.027+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_linkedin_pipeline.s3_upload_linkedin manual__2024-10-19T21:19:45.171984+00:00 [queued]>
[2024-10-19T21:19:58.027+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-10-19T21:19:58.032+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): s3_upload_linkedin> on 2024-10-19 21:19:45.171984+00:00
[2024-10-19T21:19:58.035+0000] {standard_task_runner.py:57} INFO - Started process 84 to run task
[2024-10-19T21:19:58.037+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_linkedin_pipeline', 's3_upload_linkedin', 'manual__2024-10-19T21:19:45.171984+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/linkedin_dag.py', '--cfg-path', '/tmp/tmpiuzyw9h_']
[2024-10-19T21:19:58.038+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask s3_upload_linkedin
[2024-10-19T21:19:58.056+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_linkedin_pipeline.s3_upload_linkedin manual__2024-10-19T21:19:45.171984+00:00 [running]> on host b05e8c546023
[2024-10-19T21:19:58.084+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yunus Emre KORKMAZ' AIRFLOW_CTX_DAG_ID='etl_linkedin_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload_linkedin' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T21:19:45.171984+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-19T21:19:45.171984+00:00'
[2024-10-19T21:19:59.920+0000] {logging_mixin.py:151} INFO - Bucket created
[2024-10-19T21:19:59.921+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline_linkedin.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME_LINKEDIN, file_path.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2024-10-19T21:19:59.931+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_linkedin_pipeline, task_id=s3_upload_linkedin, execution_date=20241019T211945, start_date=20241019T211958, end_date=20241019T211959
[2024-10-19T21:19:59.942+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task s3_upload_linkedin ('NoneType' object has no attribute 'split'; 84)
[2024-10-19T21:19:59.968+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-19T21:19:59.981+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
