[2024-10-13T12:45:04.211+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-10-13T12:45:01.731665+00:00 [queued]>
[2024-10-13T12:45:04.218+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-10-13T12:45:01.731665+00:00 [queued]>
[2024-10-13T12:45:04.218+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-10-13T12:45:04.225+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-10-13 12:45:01.731665+00:00
[2024-10-13T12:45:04.229+0000] {standard_task_runner.py:57} INFO - Started process 49 to run task
[2024-10-13T12:45:04.233+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-10-13T12:45:01.731665+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp6eg1ewkq']
[2024-10-13T12:45:04.235+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask reddit_extraction
[2024-10-13T12:45:04.260+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-10-13T12:45:01.731665+00:00 [running]> on host f28f66444a85
[2024-10-13T12:45:04.298+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yunus Emre KORKMAZ' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T12:45:01.731665+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-13T12:45:01.731665+00:00'
[2024-10-13T12:45:04.668+0000] {logging_mixin.py:151} INFO - connected to reddit!
[2024-10-13T12:45:04.668+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 8, in reddit_pipeline
    posts = extract_posts(instance, subreddit, time_filter, limit)
NameError: name 'extract_posts' is not defined
[2024-10-13T12:45:04.680+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20241013T124501, start_date=20241013T124504, end_date=20241013T124504
[2024-10-13T12:45:04.689+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task reddit_extraction (name 'extract_posts' is not defined; 49)
[2024-10-13T12:45:04.706+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-13T12:45:04.715+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
