[2024-10-19T19:57:58.957+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_linkedin_pipeline.linkedin_extraction manual__2024-10-19T19:57:51.301000+00:00 [queued]>
[2024-10-19T19:57:58.966+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_linkedin_pipeline.linkedin_extraction manual__2024-10-19T19:57:51.301000+00:00 [queued]>
[2024-10-19T19:57:58.966+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-10-19T19:57:58.982+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): linkedin_extraction> on 2024-10-19 19:57:51.301000+00:00
[2024-10-19T19:57:59.001+0000] {standard_task_runner.py:57} INFO - Started process 53 to run task
[2024-10-19T19:57:59.008+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_linkedin_pipeline', 'linkedin_extraction', 'manual__2024-10-19T19:57:51.301000+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/linkedin_dag.py', '--cfg-path', '/tmp/tmp7whie0a6']
[2024-10-19T19:57:59.013+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask linkedin_extraction
[2024-10-19T19:57:59.207+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_linkedin_pipeline.linkedin_extraction manual__2024-10-19T19:57:51.301000+00:00 [running]> on host b05e8c546023
[2024-10-19T19:57:59.343+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yunus Emre KORKMAZ' AIRFLOW_CTX_DAG_ID='etl_linkedin_pipeline' AIRFLOW_CTX_TASK_ID='linkedin_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T19:57:51.301000+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-19T19:57:51.301000+00:00'
[2024-10-19T19:57:59.346+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/linkedin_pipeline.py", line 8, in linkedin_pipeline
    jobs_list = extract_jobs(config_file) # manage config file
  File "/opt/airflow/etls/linkedin_etl.py", line 22, in extract_jobs
    config = load_config(config_file)
  File "/opt/airflow/etls/linkedin_etl.py", line 16, in load_config
    with open(os.path.join(os.path.dirname(__file__), file_name)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/etls/config.json'
[2024-10-19T19:57:59.354+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_linkedin_pipeline, task_id=linkedin_extraction, execution_date=20241019T195751, start_date=20241019T195758, end_date=20241019T195759
[2024-10-19T19:57:59.361+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task linkedin_extraction ([Errno 2] No such file or directory: '/opt/airflow/etls/config.json'; 53)
[2024-10-19T19:57:59.398+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-19T19:57:59.413+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
