[2024-10-19T22:04:31.738+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_linkedin_pipeline.s3_upload_linkedin manual__2024-10-19T22:04:12.609522+00:00 [queued]>
[2024-10-19T22:04:31.742+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_linkedin_pipeline.s3_upload_linkedin manual__2024-10-19T22:04:12.609522+00:00 [queued]>
[2024-10-19T22:04:31.742+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-10-19T22:04:31.747+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): s3_upload_linkedin> on 2024-10-19 22:04:12.609522+00:00
[2024-10-19T22:04:31.750+0000] {standard_task_runner.py:57} INFO - Started process 69 to run task
[2024-10-19T22:04:31.752+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_linkedin_pipeline', 's3_upload_linkedin', 'manual__2024-10-19T22:04:12.609522+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/linkedin_dag.py', '--cfg-path', '/tmp/tmppr23a2uu']
[2024-10-19T22:04:31.754+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask s3_upload_linkedin
[2024-10-19T22:04:31.773+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_linkedin_pipeline.s3_upload_linkedin manual__2024-10-19T22:04:12.609522+00:00 [running]> on host c113a6556633
[2024-10-19T22:04:31.798+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yunus Emre KORKMAZ' AIRFLOW_CTX_DAG_ID='etl_linkedin_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload_linkedin' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T22:04:12.609522+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-19T22:04:12.609522+00:00'
[2024-10-19T22:04:32.399+0000] {logging_mixin.py:151} INFO - Bucket already exists
[2024-10-19T22:04:32.400+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline_linkedin.py", line 9, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME_LINKEDIN, file_path.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2024-10-19T22:04:32.413+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_linkedin_pipeline, task_id=s3_upload_linkedin, execution_date=20241019T220412, start_date=20241019T220431, end_date=20241019T220432
[2024-10-19T22:04:32.426+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task s3_upload_linkedin ('NoneType' object has no attribute 'split'; 69)
[2024-10-19T22:04:32.450+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-19T22:04:32.461+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
